[package]
name = "validator-sampling"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5"
num-integer = "0.1.46"
num-bigint = "0.4.6"
num-rational = "0.4.2"
itertools = "0.14.0"
statrs = "0.18"
